expModelRepAll = function(){
  # this script compare predictions generated by all the models
  # create output directories
  dir.create("figures/expModelRep/")
  
  # load experiment parameters
  load('expParas.RData')
  
  # load packages and sub functions 
  library("tidyverse")
  library("latex2exp")
  source("expSchematics.R")
  source("subFxs/plotThemes.R")
  source("subFxs/helpFxs.R") 
  source("subFxs/loadFxs.R") # 
  source("subFxs/analysisFxs.R") 
  source("subFxs/modelRep.R")
  
  # load empirical data 
  allData = loadAllData()
  hdrData = allData$hdrData 
  trialData = allData$trialData       
  ids = hdrData$id[hdrData$stress == "no_stress"]
  nSub = length(ids)
  
  ## WTW from empirical data 
  source("MFAnalysis.R")
  MFResults = MFAnalysis(isTrct = T)
  sumStats = MFResults[['sumStats']]
  muWTWEmp = sumStats$muWTW
  stdWTWEmp = sumStats$stdWTW
  
  # modelNames
  models = c("BL", "optim_noise", 
             "QL1", "QL2", "RL1", "RL2")
  modelLabels =  c("BL", "ON", 
                   "Q1", "Q2", "R1", "R2")
  nModel = length(models)
  
  # num of repetitions 
  nRep = 10
  
  # loop over models
  outputs = list()
  passCheck_ = matrix(NA, nrow = nSub, ncol = nModel)
  for(m in 1 : nModel){
    modelName = models[m]
    paraNames = getParaNames(modelName)
    nPara = length(paraNames)
    
    ## check fit
    expPara = loadExpPara(paraNames, sprintf("genData/expModelFit/%s", modelName))
    passCheck = checkFit(paraNames, expPara)
    passCheck_[,m] = passCheck
    # compare willingness to wait (WTW) from empirical and replicated data
    
    ## rep
    load(sprintf("genData/expModelRep/%s_trct.RData", modelName))
    output =  data.frame(
      muAUC = repOutputs$muWTWRep_mu,
      muCIP = repOutputs$stdWTWRep_mu
    )
    outputs[[m]] = output
    rm(repOutputs)
    rm(output)
  }
  allPass = apply(passCheck_, 1, sum) == nModel
  sum(allPass)
  ######################### predict AUC #######################
  plotData = bind_rows(outputs) %>%
    mutate(model = rep(modelLabels, each = nSub),
           empAUC = rep(muWTWEmp, nModel),
           empCIP = rep(stdWTWEmp, nModel),
           condition = rep(sumStats$condition, nModel)) %>% 
    filter(rep(allPass, nModel)) %>%
    arrange(model, condition, empAUC)  %>%
    mutate(rank = rep(c(1 : sum(sumStats$condition == "HP" & allPass), 1 : sum(sumStats$condition == "LP" & allPass)), nModel)) 
  
  # full version
  plotData %>%
    ggplot(aes(rank, muAUC)) +
    geom_bar(data = plotData[plotData$model == "Q1",],
             aes(rank, empAUC), inherit.aes = F, stat = "identity",
             fill = NA, color = "grey") +
    geom_line(aes(color = model)) + 
    geom_point(aes(color = model)) + 
    myTheme + 
    ylab("AUC (s)") + xlab("") +
    facet_grid(~condition) +
    scale_x_continuous(breaks = c()) +
    xlab('') +
    scale_color_manual(values = c(
      "#fb9a99",
      "#e31a1c",
      "#b2df8a",
      "#33a02c",
      "#a6cee3",
      "#1f78b4"
    )) +
    scale_shape_manual(values = c(NA, 16)) + 
    theme(legend.title = element_blank(),
          legend.position = "none")
  fileName = "figures/expModelRep/AUC_all_full.eps"
  ggsave(filename = fileName,  width = 6, height = 3)
  fileName = "figures/expModelRep/AUC_all_full.png"
  ggsave(filename = fileName,  width = 6, height = 3)
  
  ######################### predict CIP #######################
  plotData = bind_rows(outputs) %>%
    mutate(model = rep(modelLabels, each = nSub),
           empAUC = rep(muWTWEmp, nModel),
           empCIP = rep(stdWTWEmp, nModel),
           condition = rep(sumStats$condition, nModel)) %>% 
    filter(rep(allPass, nModel)) %>%
    arrange(model, condition, empCIP)  %>%
    mutate(rank = rep(c(1 : sum(sumStats$condition == "HP" & allPass), 1 : sum(sumStats$condition == "LP" & allPass)), nModel),
           type = ifelse(model %in% c("optim_noise", "optim_noise_bias"),
                         "baseline", "RL")) 
  # full version
  plotData %>%
    ggplot(aes(rank, muCIP)) +
    geom_bar(data = plotData[plotData$model == "Q1",],
             aes(rank, empCIP), inherit.aes = F, stat = "identity",
             fill = NA, color = "grey") +
    geom_line(aes(color = model)) + 
    geom_point(aes(color = model)) + 
    myTheme + 
    ylab(TeX("CIP ($s^2$)")) + xlab("") +
    facet_grid(~condition) +
    scale_x_continuous(breaks = c()) +
    xlab('') +
    scale_color_manual(values = c(
      "#fb9a99",
      "#e31a1c",
      "#b2df8a",
      "#33a02c",
      "#a6cee3",
      "#1f78b4"
    )) +
    scale_linetype_manual(values = c(2, 1)) +
    scale_shape_manual(values = c(NA, 16)) + 
    theme(legend.title = element_blank(),
          legend.position = "none")
  fileName = "figures/expModelRep/CIP_all_full.eps"
  ggsave(filename = fileName,  width = 6, height = 3)
  fileName = "figures/expModelRep/CIP_all_full.png"
  ggsave(filename = fileName,  width = 6, height = 3)
  
}




